version: "3"

services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/api
    command: sh -c "python manage.py runserver 0.0.0.0:8080"

  api2:
    build:
      context: .
    ports:
      - "8080:8080"

